spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: lb://customers-service
          predicates:
            - Path=/api/customers,/api/customers/**
          filters:
              - StripPrefix=1
              - PrefixPath=/api/v1

           - id: accounts
          uri: lb://account-service
          predicates:
            - Path=/api/accounts,/api/accounts/**
          filters:
              - StripPrefix=1
              - PrefixPath=/api/v1
         
